cache:
  url: localhost
  #user:
  #pass:
  port: 6379
apis: 
- name: "address-api"
  url: address-api:5000
  path: /api/postal/
  fallback: true
- name: "external-api"
  url: https://external-api.com
  path: /api/postal/
 