cache:
  url: localhost
  #user:
  #pass:
  protocol: tcp
  port: 6379
apis: 
- name: "address_api"
  url: address-api:5000
  path: /api/postal/
  fallback: true
- name: "external_api"
  url: https://external-api.com
  path: /api/postal/
 